### ISSUE TITLE
Client crash, midnight, iceandfire

### ISSUE THREAD

**Issue by dazadazu** [Axanthic-Game-Studios/Lands-of-Icaria#3]
Vanillafix crashes client saying its "themidnight" mod. When removing midnight it then says the culprit is "iceandfire" mod. When removing Lands of Icaria no client crash persists and boots up normally.

// Hey, that tickles! Hehehe!

Time: 2021-04-04 20:51:37 PDT
Description: Initializing game

java.lang.RuntimeException: Duplicate stat id: "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.siren.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" and "TranslatableComponent{key='stat.entityKill', args=[TranslatableComponent{key='entity.siren.name', args=[], siblings=[], style=Style{hasParent=true, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}" at id stat.killEntity.siren
    at net.minecraft.stats.StatBase.registerStat(SourceFile:41)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder.registerStatistics(EntityEntryBuilder.java:285)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder.access$100(EntityEntryBuilder.java:57)
    at net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry.addedToRegistry(EntityEntryBuilder.java:335)
    at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:509)
    at net.minecraftforge.registries.GameData$EntityCallbacks.onAdd(GameData.java:500)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:350)
    at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:281)
    at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:113)
    at com.github.alexthe666.iceandfire.CommonProxy.registerSpawnable(CommonProxy.java:141)
    at com.github.alexthe666.iceandfire.CommonProxy.registerEntities(CommonProxy.java:95)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1414_CommonProxy_registerEntities_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 596379112 bytes (568 MB) / 2415919104 bytes (2304 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 425 mods loaded, 424 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

**Comment by RCXcrafter** [comment]
Can you give me a full crash log with the get link button from vanillafix?

**Comment by dazadazu** [comment]
[crash-2021-04-10_00.31.50-client.txt](https://github.com/Axanthic-Game-Studios/Lands-of-Icaria/files/6289424/crash-2021-04-10_00.31.50-client.txt)
